name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
    - name: Install system deps
      run: pacman  --noconfirm -Syu ffmpeg rustup gcc clang pkgconf vulkan-headers
    - name: Install rust
      run: rustup install stable
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose --locked --all-features
    - name: Format
      run: cargo fmt --check
    #- name: Run tests
    #  run: cargo test --verbose
